"""
Interface definitions for Event Bus & Real-Time Session Streaming.
Defines the pub/sub contract for dispatching session events to WebSockets and Slack.
"""

import time
from abc import ABC, abstractmethod
from collections.abc import AsyncIterator
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class EventType(str, Enum):
    TOKEN = "token"  # Streaming text token
    REASONING_TOKEN = "reasoning_token"  # Streaming thought/reasoning token
    STATUS_CHANGED = "status_changed"  # Agent state or progress message
    TOOL_STARTED = "tool_started"  # Tool execution initiated
    TOOL_COMPLETED = "tool_completed"  # Tool execution completed with output
    FILE_DIFF = "file_diff"  # File modified with diff content
    DECISION_REQUIRED = "decision_required"  # Interactive decision card prompt
    DECISION_SUBMITTED = "decision_submitted"  # User response to decision card
    LOG_CHUNK = "log_chunk"  # Raw ANSI execution log chunk
    SANDBOX_STATE = "sandbox_state"  # Running, hibernated, starting
    SESSION_UPDATED = "session_updated"  # Session metadata (title, etc.) updated
    PLAN_UPDATED = "plan_updated"  # Agent plan/checklist updated with tasks
    FOLLOWUP_SUGGESTION = "followup_suggestion"  # Probable next question generated by LLM
    SUBAGENT_STARTED = "subagent_started"  # Specialized subagent spawned
    SUBAGENT_PROGRESS = "subagent_progress"  # Nested subagent reasoning or tool event
    SUBAGENT_COMPLETED = "subagent_completed"  # Subagent turn finished with findings
    ERROR = "error"  # Unrecoverable or tool error


@dataclass
class SessionEvent:
    session_id: str
    event_type: EventType
    payload: dict[str, Any]
    timestamp_ms: int = field(default_factory=lambda: int(time.time() * 1000))


class EventBusProtocol(ABC):
    """
    Contract for broadcasting session events across API WebSockets,
    background workers, and the Slack Assistant bot.
    """

    @abstractmethod
    async def publish(self, event: SessionEvent) -> None:
        """Publishes an event to the session topic."""
        pass

    @abstractmethod
    def subscribe(
        self,
        session_id: str,
        client_id: str | None = None,
    ) -> AsyncIterator[SessionEvent]:
        """
        Subscribes to all real-time events for a specific session.
        Used by the WebSocket endpoint to stream events to Next.js.
        """
        pass
