apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocket-chat.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rocket-chat.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.backend.service.port | default 8000 }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.backend.service.type "NodePort") .Values.backend.service.nodePort }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- end }}
  selector:
    {{- include "rocket-chat.backendSelectorLabels" . | nindent 4 }}
