{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rocket-chat.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rocket-chat.labels" . | nindent 4 }}
{{- end }}
